### PR TITLE
Add light/dark mode switching

### PR DESCRIPTION
**Pull request by thrownness**
Added switching between light and dark styles.

2020-03-05 22_14_52-style css - iris-messenger - Visual Studio Code

The core logic of this is at the top of `index.html`.

You can alter primary app colors in the `light.css` and `dark.css` files and they will update in the main `style.css` file where the  [css variables](https://caniuse.com/#feat=css-variables) are linked. 

I hope this can be of help. Let me know if you have feedback.

### CODE REVIEW

**Comment by mmalmi** [comment]
Thanks for the PR!

Some things I noticed: "not seen" checkmarks are not visible. "Not seen by them" notification button was black. Also, when I tested https://deploy-preview-5--iris-chat.netlify.com/ on Android (Samsung Internet browser), it only showed a black screen. Not sure if it was because of this commit or something else.

Screenshot 2020-03-11 at 12 23 17

**Comment by thrownness** [comment]
Thanks for the feedback! I'll fix those things. I also was thinking about changing the text input and emoji selector to switch themes as well.

After those changes, I'll look into possible issues with Samsung's browser. Can you try it with a different android browser just to see? @mmalmi

**Comment by thrownness** [comment]
@mmalmi I think the screen goes blank when a browser blocks cookies from being used. I just tried to load iris locally in Microsoft Edge and the whole screen was pure white. But then when I selected "allow cookies" for the page, it loaded correctly.

**Comment by thrownness** [comment]
Fixed:
- [X]  "not seen" checkmarks in the chat list are not visible
- [X]  "Not seen by them" notification button was black
- [X]  "Login" screen color is still light blue

image

image

- [ ]  When I tested https://deploy-preview-5--iris-chat.netlify.com/ on Android (Samsung Internet browser), it only showed a black screen. Not sure if it was because of this commit or something else.

This is still an open question, but I believe it is related to the browser not loading the site because it is rejecting cookies from the app.

**Comment by mmalmi** [comment]
Looking pretty good! Only link color (visited color also) should be something else in the dark theme:

Screenshot 2020-03-12 at 16 47 15

**Comment by mmalmi** [comment]
When it comes to choosing the colors, copying saturation & brightness from Twitter and hue from the Iris logo can be a good idea: https://github.com/irislib/iris/blob/master/brand/iris_icon_blue_rgb_512.png

**Comment by thrownness** [comment]
One of the things that I'd like to do is consolidate colors wherever possible.

```css
/* light.css: 👉 dark-on-light */
:root {
    --text-color: #262626;
    --text-time: rgba(0, 0, 0, 0.45);
    --main-color: #e5ddd5;
    --header-color: #efefef;
    --chat-active: #eaeaea;
    --chat-hover: #f3f3f3;
    --msg-content-background: #ffffff;
    --our-msg: #d7f7c5;
    --notify: #9ee8ff;
    --login-background: #70d4f2;
    --seen-indicator: rgba(0, 0, 0, 0.45);
}
```

For example, combine `notify` and `login-background` into the same color. And `header-color`, `chat-active`, `chat-hover`, and `msg-content-background` are all _so_ similar too. Using CSS variables helps us to better see where we can be more consistent / intentional with the choices.

**Pull request merged**
