### PR TITLE
feat: add support for nip42 authentication

### PR DESCRIPTION
**Pull request by npub1zenn0**
Fixes https://github.com/irislib/iris-messenger/issues/364

Dunno if I need to do testing for android/ios? I didn't do any of that. Also on the `loki`/db I'm _not really sure_ if I did everything I needed here. Help appreciated on that regard, you can maybe save me a lot of effort if you know.

I didn't see any "toast" method or anything, so I didn't really build user feedback on rejected events there. It's probably obvious to user that know, but very confusing to those that don't. However, that'll be 1 user in 10000.

Here's a gif:

- add relay, it asks for signature
  - I made it auto-ask for the signature, because otherwise the flow with "permanent permissions" will be bad
  - It only asks once, until you try ticking the checkbox again
  - in the gif the "accept" rejects too bc I'm not authorized
- I did not test the success flow, I don't have any sats on lightning atm so I can't register on the paid ones. Would be surprised if it didn't work, tho. I will test it as soon as I have some available

preview

(semi-related: I already opened a pr on the auth changes to upstream https://github.com/nbd-wtf/nostr-tools/pull/190 , it's mostly the same code.)

### CODE REVIEW

**Comment by npub1zenn0** [comment]
Looks like I missed the "relayPool" part. It even seems that, based on devtools, relays get connected to multiple times, and the AUTH request only appears in one of the sockets. I'll have to look into that.

**Comment by npub1zenn0** [comment]
I think we good now.

I fixed some bugs on the network settings panel while at it.

**Comment by npub1zenn0** [comment]
Fixed the lint for ya

**Comment by mmalmi** [comment]
Just tested with wss://filter.nostr.wine, seems to work. Thank you, this is one of the best pull requests to Iris so far!

**Comment by mmalmi** [comment]
Btw, should this only authenticate servers on your own relay list?

If you automatically authenticate everything, a rogue relay in someone's profile could forward you an auth request from a private relay and forward it to you to be automatically signed.

**Comment by npub1zenn0** [comment]
The auth event that is signed includes the calling relay's url, so that shouldn't be an issue. It'd be the rogue relay's auth then, and not be valid for another relay.

https://github.com/irislib/iris-messenger/pull/370/files#diff-e3b002bb3ec1d51f2cd6b29c77717903d45d05d46c4555b78a1c053e5923537dR22-R30

**Comment by mmalmi** [comment]
Ah, should be fine then if nostr-tools/nip42 and relays check the tag correctly.

**Pull request merged**
