### PR TITLE
Review the mobile bottom toolbar

### PR DESCRIPTION
**Pull request by dtonon**
Minor tweaks to improve UI and UX:

* Purple color for the "new message" icon to make it more visibile
* New highligh/fade logic: selected element fades out (including the identicon) because is not clickable anymore and there is no need to focus it when the section is shown

Preview:

iris-toolbar

### CODE REVIEW

**Comment by mmalmi** [comment]
I think the current logic of highlighting the active item is good. But the purple color of the "new message" icon could work.

**Comment by dtonon** [comment]
> I think the current logic of highlighting the active item is good — that's how it works in most applications.

I was not 100% sure but using it a little time wasn't bad.
The avantage of the current solution is that is less distracting, but we could fade the identicon too.

> But the purple color of the "new message" icon could work

Yes this was the main point for which I started tweaking the toolbar :)

**Comment by dtonon** [comment]
Perhaps toolbar icons' design should be alligned with the note ones, i.e. lighter (search) and outlined (home).
If you agree I can try to redesign them before merging the PR.

**Comment by dtonon** [comment]
@mmalmi what do you think about this icons?

Screenshot 2023-01-08 alle 23 10 18

I reverted to the previous fade mode.

I see you put a circle around the active identicon, so I don't push the idea to fade out when not select. The circle color is "button-bg-hover", I used (inline sorry, now refactored) #8473b3 for the new button, the send one and the textarea border. I think it is better to rationalize the colors choise and don't let proliferate, right?

Now "button-bg" and "button-bg-hover" are used only in the profile page, I tried to use my color and a slight darker version for the over:

Screenshot 2023-01-08 alle 23 27 20

Update pushed, let me know what you think!

**Comment by dtonon** [comment]
@mmalmi I just noticed that the lens icon used in the top and the one used for the global feed have the same source, so my change to the global (the world) was applied to the top too. Updated:

Screenshot 2023-01-09 alle 00 36 42

**Comment by mmalmi** [comment]
Thanks! Merged, but restored the original home icon. The pin icon looked like location tag, and a bit unclear what it means.

This android client looks interesting: https://iris.to/#/post/note1ha2zd5gatagemcar4f84hdw0pyhtpaauq9kkgheu8cjhr477979qdgzjr6

I think we could instead of "Home" have a similar "Feed" tab which allows you to select from follows, trending, global and other feeds.

**Comment by dtonon** [comment]
> The pin icon looked like location tag

You are right, home icon is now the standard, use it improve UX.

> I think we could instead of "Home" have a similar "Feed" tab which allows you to select from follows, trending, global and other feeds.

Snort.social ha a similar approach in the main view with Follows and Global button, I like it.
Perhaps I will add a switch to view all or only main post too (like Damus does), because replies can create a lot of noise both in the Follows and Global feed.

**Pull request merged**
