### PR TITLE
Displays "Note to self" when you open a convo with yourself

### PR DESCRIPTION
**Pull request by thrownness**
image

### CODE REVIEW

**Comment by mmalmi** [comment]
Nice idea! Just some things to consider:

- [ ] "Note to self" text should have a different color or be otherwise distinguishable from nicknames, so you can't confuse others by setting your name to "Note to self".
- [ ] When navigating to your profile page, it should show your name again (not "Note to self")

**Comment by thrownness** [comment]
@mmalmi This actually doesn't use the `put` method at all! It's literally just a UI change.

I found that a lot of new users would accidentally open a conversation with themselves (because of the UI on the New Chat page (which I updated in #7 )). 

This PR will just reflect that it's ok to open a convo with yourself because it actually then makes a neat little note to self channel :)

**Comment by mmalmi** [comment]
> @mmalmi This actually doesn't use the `put` method at all! It's literally just a UI change.

Oops, I mixed it up with your other PRs!

> Which profile page? Do you mean the Settings page when you click on the top left? Or do you mean your profile which you see if you click on "note to self" in the header of the "note to self" channel?

The latter one.

**Comment by thrownness** [comment]
@mmalmi How about this for making the "note to self" text look different? 
image

And it no longer shows when you're on your own profile page 
image

**Comment by mmalmi** [comment]
Thanks!

**Pull request merged**
