### PR TITLE
The nickname update

### PR DESCRIPTION
**Pull request by thrownness**
I apologize in advance, but there are some formatting / layout changes bundled with this.

image

## Functional Changes

Ability to add a nickname via the other user's profile page. Upon adding the nickname, it will update in the header as well as on the left sidebar. The user's public name will still appear in the "nicknames" section.

## Layout Changes

The `New Chat` (see images below) and `Profile` (see image above) pages got some necessary layout improvements to make things easier to scan quickly. 

I also fixed a minor bug that exists today: The `profile-about` text was not properly resetting as you navigate between profiles

Before: 
image

After: image

### CODE REVIEW

**Comment by thrownness** [comment]
I just added the feature to make nicknames editable by both parties (so they can also see each others' edits).

I also changed the UI a little bit to better mirror how FB Messenger does things (this is where I got the great idea from).

**Comment by thrownness** [comment]
I suppose the functions need to be updated for the new API changes that just went out in production?

**Comment by thrownness** [comment]
@mmalmi ok I updated this for the new API.

**Comment by mmalmi** [comment]
Did a few edits using github's editor. As the application grows in complexity, a web framework starts to sound like a good idea.

**Pull request merged**
