### PR TITLE
Update home / new / global icons + Fix vertical alignament

### PR DESCRIPTION
**Pull request by dtonon**
Increased a bit the size:

immagine

Refactored the svg structure for maintainability.

### CODE REVIEW

**Comment by dtonon** [comment]
@mmalmi please wait to merge, I'm tweaking some size/alignment of other icons

**Comment by dtonon** [comment]
@mmalmi committed more fix and updated the pr description.
Final version:

immagine

**Comment by dtonon** [comment]
@mmalmi committed more fixes and updated the PR description.
Final version:

immagine

**Comment by mmalmi** [comment]
Size and vertical alignment 👍  But can we change back to the old icons? I like them better — globe is more recognizable and "new note" button is simpler.

**Comment by dtonon** [comment]
Done e pushed:

Screenshot 2023-01-12 alle 13 07 53

But I'm not so conviced, they seem picked from different sources :)
Perhaps they should be all outlined, and filled when clicked.

And I would experiment with a slight different structure too, more inclined to content *production* (instead of consumation), prompring more the post button.
Quick mockup:

immagine

This a little non standard toolbar, without loose any usability, would also make Iris more recognizable on mobile, a plus for the brand ;)

**Comment by dtonon** [comment]
Or a more standard version with outlined icons and new post / profile filled but putted at the left/right sides: The home is central and highlighted by a circle:

immagine

**Comment by mmalmi** [comment]
Changes are not pushed yet

**Comment by mmalmi** [comment]
Btw, netlify builds previews of pull requests. You can find the link below, scrolling down under "All checks have passed". https://deploy-preview-185--iris-messenger.netlify.app/

**Comment by dtonon** [comment]
> Btw, netlify builds previews of pull requests

Nice!
Sorry, rebased and pushed.

**Comment by dtonon** [comment]
@mmalmi any comment about the other proposed solutions?

**Comment by mmalmi** [comment]
iris-iphone-screenshot

I think here's the reason why I made the vertical alignment not centered in the first place. Not much space between the iphone bar and footer icons. I wonder if there's some clean solution to showing it differently on iPhone. But I'll keep the changes from this pull request for now.

**Comment by dtonon** [comment]
> I think here's the reason why I made the vertical alignment not centered in the first place.

Oh, I see.
I don't have an iPhone to test, I will check with a colleague.

Because we are exploring this area, and about  [other](https://github.com/irislib/iris-messenger/pull/185#issuecomment-1380255409) [proposals](https://github.com/irislib/iris-messenger/pull/185#issuecomment-1380267676)? They make any sense to you?

**Pull request merged**
