### PR TITLE
add Shavian transliteration for English

### PR DESCRIPTION
**Pull request by trosel**
`Shaw` in ISO 15924 https://en.wikipedia.org/wiki/ISO_15924

### CODE REVIEW

**Comment by mmalmi** [comment]
We need lazy-loading for translations so they don't slow down opening the app. Then we can add shavian, pirate english, klingon and other cool and useful languages 😄

**Comment by trosel** [comment]
@mmalmi Good point! Do you have any libraries in mind to enable lazy loading of translations?

**Comment by mmalmi** [comment]
It can be done with import(). Here's an example: https://github.com/irislib/iris-messenger/blob/0b6c0bee79f50fe546567d18069c5cc991b0d8a5/src/js/QRScanner.js#L20

It just requires making my translation function asynchronous, which is not straightforward.

**Comment by trosel** [comment]
i think adding more niche translations is a good way to get more exposure / users too btw. you already have some great translations for this

**Pull request closed without merging**
