### PR TITLE
Stop sending empty kind:6 events. use kind:1 with a reference instead.

### PR DESCRIPTION
**Pull request by fiatjaf**
Empty kind 6 events were a wrong NIP, no one implements them.

https://github.com/nostr-protocol/nips/blob/master/10.md has a safer way to "retweet" that most clients implement.

### CODE REVIEW

**Comment by mmalmi** [comment]
I think kind 6 was used by Damus? Has that changed?

**Comment by fiatjaf** [comment]
Damus sends kind 6 as the full content of the event being reposted a string inside `content`, which is a UX decision from them but I think it is an antipattern. They are currently blocking empty kind 6 events.

**Comment by fiatjaf** [comment]
I can rebase if you approve.

**Comment by mmalmi** [comment]
Thanks for the PR! I was wondering how these boost events work.

**Comment by mmalmi** [comment]
Unfortunately this caused a weird issue where tags array ordering would be wrong, and #[0] would refer to the 'p' tag, not 'e'. Maybe something related to typescript compiler? Idk.

```
        Nostr.publish({
          kind: 1,
          tags: [
            ['e', nostrId, '', 'mention'],
            ['p', author],
          ],
          content: '#[0]',
        });
```

Reverted to kind 6 events until this can be sorted out. But handling of incoming kind 1 boosts is still there.

**Comment by fiatjaf** [comment]
Are you sure? I did test this locally and got a boost as expected.

I don't understand how 0 could be the second item in an array. Maybe these tag arrays are shuffled or reordered somewhere inside `.publish()`?

**Comment by Saibato** [comment]
@mmalmi @fiatjaf yeah, that was a strange weird at first frightening error, a function call to reverse(), changed the tag order internally.
here a patch on current master that will allow kind 1 boots in iris
``` diff
diff --git a/src/js/Nostr.ts b/src/js/Nostr.ts
index f5886834..3cb6662a 100644
--- a/src/js/Nostr.ts
+++ b/src/js/Nostr.ts
@@ -817,6 +817,7 @@ export default {
   },
   handleBoost(event: Event) {
     const id = event.tags.reverse().find((tag: any) => tag[0] === 'e')?.[1]; /$
+    event.tags.reverse()
     if (!id) return;
     if (!this.boostsByMessageId.has(id)) {
       this.boostsByMessageId.set(id, new Set());
diff --git a/src/js/components/PublicMessage.js b/src/js/components/PublicMessa$
index 94e6ed48..0333c27a 100644
--- a/src/js/components/PublicMessage.js
+++ b/src/js/components/PublicMessage.js
@@ -220,7 +220,7 @@ class PublicMessage extends Message {
       const nostrId = Nostr.toNostrHexAddress(this.props.hash);
       if (nostrId) {
```

or merge PR https://github.com/Saibato/iris-messenger/commit/039074ee71d021d86137f189cf41cdf70640ed8b

**Comment by mmalmi** [comment]
> @mmalmi @fiatjaf yeah, that was a strange weird at first frightening error, a function call to reverse(), changed the tag order internally. here a patch on current master that will allow kind 1 boots in iris
> 
> ```diff
> diff --git a/src/js/Nostr.ts b/src/js/Nostr.ts
> index f5886834..3cb6662a 100644
> --- a/src/js/Nostr.ts
> +++ b/src/js/Nostr.ts
> @@ -817,6 +817,7 @@ export default {
>    },
>    handleBoost(event: Event) {
>      const id = event.tags.reverse().find((tag: any) => tag[0] === 'e')?.[1]; // last e tag is the liked post
> +    event.tags.reverse()
>      if (!id) return;
>      if (!this.boostsByMessageId.has(id)) {
>        this.boostsByMessageId.set(id, new Set());
> diff --git a/src/js/components/PublicMessage.js b/src/js/components/PublicMessage.js
> index 94e6ed48..0333c27a 100644
> --- a/src/js/components/PublicMessage.js
> +++ b/src/js/components/PublicMessage.js
> @@ -220,7 +220,7 @@ class PublicMessage extends Message {
>        const nostrId = Nostr.toNostrHexAddress(this.props.hash);
>        if (nostrId) {
>          Nostr.publish({
> -          kind: 6,
> +          kind: 1,
>            tags: [
>              ['e', nostrId, '', 'mention'],
>              ['p', author],
> ```
> 
> or merge PR [Saibato@039074e](https://github.com/Saibato/iris-messenger/commit/039074ee71d021d86137f189cf41cdf70640ed8b)

Oh, `array.reverse()` changed the array in place and caused the bug! Thanks for noticing.

**Comment by mmalmi** [comment]
I changed to event kind 6 with content `#[0]` since it displays least bad on Snort and Damus.

I wonder what's the reasoning behind Damus reposting the whole event content.

**Comment by fiatjaf** [comment]
> kind 6 with content #[0]

Really? I had never heard about this. This is not in the spec, was never discussed anywhere, and as far as I know no other client supports it and Damus and Snort should also not be supporting it. We should all strive to implement only 1 way of doing each thing, otherwise the protocol can get increasingly bloated and the only thing we will achieve with so many "features" is double, triple, quadruple the work that everybody else must do forever.

> I wonder what's the reasoning behind Damus reposting the whole event content. Sounds like unnecessary duplication, and you might even set a content that's different than the tagged note.

I agree it is an anti-pattern and I think we shouldn't be encouraging it. The justification is "performance".

**Pull request merged**
