### PR TITLE
Compact quoted messages to improve readibility

### PR DESCRIPTION
**Pull request by dtonon**
@mmalmi a first quick and dirty proposal to compact the quoted messages, before - after:

immagine

Two rows of text are enoght to grasp the context, mostly on the notifications.

The solution is not optimal when the note has an image, I'm working on it. Perhaps just increasing a bit the height in this particular case will solve the matter.

### CODE REVIEW

**Comment by dtonon** [comment]
Improve the image quoting with a higher space (webkit only):

Screenshot 2023-01-11 alle 12 53 46

@mmalmi in this specific case I would disable the image zoom, otherwise the user is unable to reach the note with a click.

**Comment by dtonon** [comment]
PS: The linter fails on files not commited by me

**Comment by mmalmi** [comment]
In feed I want to see the whole replied message. In notifications, it's true that the whole message doesn't need to be displayed. For notifications we should do a separate component that shows only the essential information.

**Comment by dtonon** [comment]
You are right, in the feed the quoted message is useful. Unluckly I cannot differentiate feed and notifications without an ID/class in the html. I suggest to add one to the body for everty section: feed, global, notifications, post.

Btw I think that an user option that tweak a CSS class to apply this visualization on the feed/global is a good option, easy to achieve.

**Pull request closed without merging**
